services:
  - type: web
    name: ceol-io
    env: python
    buildCommand: "pip install -r requirements.txt && npm install && npm run build"
    startCommand: "flask --app app run --host=0.0.0.0"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: "18"

  - type: cron
    name: ceol-io-active-sessions
    env: python
    schedule: "14,29,44,59 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 jobs/check_active_sessions.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PGHOST
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGPORT
        value: "5432"

  - type: web
    name: abc-renderer
    runtime: node
    rootDir: abc-renderer
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: PORT
        value: "10000"